trigger:
- main

variables:
- group: Secure Secrets

pool:
  name: Default

stages:
# ----------------------------------
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Building and Testing the app'
    steps:
    - script: python3 --version
      displayName: 'Check local Python version'

    - script: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        source venv/bin/activate
        python3 -m unittest discover
      displayName: 'Run Unit Tests'

    - script: |
        echo "Build completed successfully!"
      displayName: 'Build complete'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)'
        artifactName: 'drop'
      displayName: 'Publish Build Artifact'

# ----------------------------------
- stage: Release
  displayName: 'Release Stage'
  dependsOn: Build
  jobs:
  - job: ReleaseJob
    displayName: 'Release/Deploy Job'
    steps:
    - download: current
      artifact: drop

    - script: |
        echo "Deploying To-Do App..."
      displayName: 'Simulate Deployment'

    - script: |
        echo "The secret password is: $(DATABASE-PASSWORD-TD)"
      displayName: 'Use Secure Variable'
