trigger:
- main

pool:
  name: Default

stages:
# ----------------------------------
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Building and Testing the app'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        source venv/bin/activate
        python -m unittest discover
      displayName: 'Run Unit Tests'

    - script: |
        echo "Build completed successfully!"
      displayName: 'Build complete'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)'
        artifactName: 'drop'
      displayName: 'Publish Build Artifact'

# ----------------------------------
- stage: Release
  displayName: 'Release Stage'
  dependsOn: Build
  jobs:
  - job: ReleaseJob
    displayName: 'Release/Deploy Job'
    steps:
    - download: current
      artifact: drop

    - script: |
        echo "Deploying To-Do App..."
      displayName: 'Simulate Deployment'

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'AzureConnection'
        KeyVaultName: 'todoappvaulttedidobi'
        SecretsFilter: 'DATABASE-PASSWORD-TD'
      displayName: 'Fetch Secret from Key Vault'

    - script: |
        echo "The secret password is: $(DATABASE-PASSWORD-TD)"
      displayName: 'Use the Secret from Key Vault'
