trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "Running application test step"
  displayName: 'Test app'

- script: |
    echo "Build finished successfully!"
  displayName: 'Build Complete'
